language: python

matrix:
  include:
  - env: TOX_ENV=py35-django-22
    python: "3.5"
  - env: TOX_ENV=py36-django-22
    python: "3.6"
  - env: TOX_ENV=py36-django-30
    python: "3.6"
  - env: TOX_ENV=py37-django-22
    python: "3.7"
  - env: TOX_ENV=py37-django-30
    python: "3.7"
  - env: TOX_ENV=py36-django-30-cypress
    python: "3.6"
  fast_finish: true

install: "pip install -r requirements_test.txt"
before_script: "npm install"
script:
    - "tox -e $TOX_ENV"

after_success:
    - "codecov -e TOX_ENV"
